In [5]:
import torch

In [6]:
if torch.cuda.is_available():
    print("GPU is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU is not available. Using CPU")


GPU is available
Using GPU: NVIDIA GeForce RTX 2050


In [7]:
a=torch.empty(2,3)
a=a*100

In [8]:
a
type(a)

torch.Tensor

In [9]:
# using zeros
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [10]:
# using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [11]:
torch.rand(4,5)

tensor([[0.0936, 0.1043, 0.8418, 0.7007, 0.6191],
        [0.2732, 0.1253, 0.3785, 0.6381, 0.8312],
        [0.2915, 0.4313, 0.3994, 0.4596, 0.0549],
        [0.3159, 0.4058, 0.3675, 0.5131, 0.5373]])

In [12]:
# use of seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [13]:
tsr=torch.tensor([[1,2,3],[3,4,5]])
tsr

tensor([[1, 2, 3],
        [3, 4, 5]])

In [14]:
torch.arange(0,10,2)

tensor([0, 2, 4, 6, 8])

In [15]:
torch.linspace(0,10,10)

tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])

In [16]:
torch.eye(6)

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 1.]])

In [17]:
torch.full((3,4),9)

tensor([[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]])

In [18]:
# shapes
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
x.shape

torch.Size([2, 3])

In [20]:
torch.empty_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [21]:
x.dtype

torch.int64

In [22]:
y=torch.tensor([1.0,2.0,3.5,5.6,9.2],dtype=torch.int32)
y

tensor([1, 2, 3, 5, 9], dtype=torch.int32)

In [23]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [24]:
# mathematical operation

x=torch.rand(2,2)
print(x+2)
print(x*2)
print(x-2)
print((x*100)/2)
print((x*100)//2)
print(((x*100)//2)%2)

tensor([[2.2627, 2.0428],
        [2.2080, 2.1180]])
tensor([[0.5254, 0.0857],
        [0.4161, 0.2361]])
tensor([[-1.7373, -1.9572],
        [-1.7920, -1.8820]])
tensor([[13.1345,  2.1420],
        [10.4014,  5.9019]])
tensor([[13.,  2.],
        [10.,  5.]])
tensor([[1., 0.],
        [0., 1.]])


In [25]:
a=torch.tensor([[1,2,3,4],[5,6,7,8]])
b=torch.tensor([[1,2,3,4],[5,6,7,8]])
print(a+b)
print(a-b)
print(a*b)
print(a/b)
print(a**b)

tensor([[ 2,  4,  6,  8],
        [10, 12, 14, 16]])
tensor([[0, 0, 0, 0],
        [0, 0, 0, 0]])
tensor([[ 1,  4,  9, 16],
        [25, 36, 49, 64]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([[       1,        4,       27,      256],
        [    3125,    46656,   823543, 16777216]])


In [26]:
torch.abs(a)

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8]])

In [27]:
torch.negative(a)

tensor([[-1, -2, -3, -4],
        [-5, -6, -7, -8]])

In [28]:
d=torch.tensor([1.3,4.5,7.8,9.2])
torch.round(d)

tensor([1., 4., 8., 9.])

In [29]:
torch.ceil(d)

tensor([ 2.,  5.,  8., 10.])

In [30]:
torch.floor(d)

tensor([1., 4., 7., 9.])

In [31]:
torch.clamp(d,min=2,max=3)

tensor([2., 3., 3., 3.])

In [32]:
# reduction operation

x=torch.randint(size=(4,5),low=0,high=10)
x

tensor([[4, 3, 8, 8, 4],
        [4, 1, 0, 4, 3],
        [8, 7, 4, 6, 0],
        [1, 9, 9, 8, 0]])

In [33]:
torch.sum(a)

tensor(36)

In [34]:
torch.sum(a,dim=0)

tensor([ 6,  8, 10, 12])

In [39]:
c=torch.tensor([[1,2,3,4],[5,6,7,8]],dtype=torch.float32)
torch.mean(c)

tensor(4.5000)

In [40]:
torch.median(c)

tensor(4.)

In [42]:
torch.prod(c)

tensor(40320.)

In [43]:
torch.var(c)

tensor(6.)

In [44]:
torch.std(c)

tensor(2.4495)

In [45]:
# biggest value position
torch.argmax(c)

tensor(7)

In [46]:
torch.argmin(c)

tensor(0)

In [49]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
torch.matmul(f,g)

tensor([[ 59, 127],
        [ 18,  47]])

In [54]:
f=torch.tensor([1,2])
g=torch.tensor([1,2])
torch.dot(f,g)

tensor(5)

In [57]:
f=torch.randint(size=(2,3),low=0,high=10)
torch.transpose(f,0,1)

tensor([[3, 6],
        [8, 2],
        [5, 9]])

In [63]:
f=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
torch.det(f)

tensor(-558.)

In [65]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(2,3),low=0,high=10)
f<g

tensor([[False, False, False],
        [False, False,  True]])

In [66]:
g<f

tensor([[False, False, False],
        [ True,  True, False]])

In [67]:
g==f

tensor([[ True,  True,  True],
        [False, False, False]])

In [68]:
torch.log(g)

tensor([[0.6931, 1.0986, 1.9459],
        [  -inf, 0.6931, 1.6094]])

In [69]:
torch.exp(g)

tensor([[7.3891e+00, 2.0086e+01, 1.0966e+03],
        [1.0000e+00, 7.3891e+00, 1.4841e+02]])

In [70]:
torch.sqrt(g)

tensor([[1.4142, 1.7321, 2.6458],
        [0.0000, 1.4142, 2.2361]])

In [71]:
torch.sigmoid(g)

tensor([[0.8808, 0.9526, 0.9991],
        [0.5000, 0.8808, 0.9933]])

In [73]:
g=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
torch.softmax(g,dim=0)

tensor([[0.5000, 0.9526, 0.0474],
        [0.5000, 0.0474, 0.9526]])

In [74]:
torch.relu(g)

tensor([[2., 8., 0.],
        [2., 5., 3.]])